### PR TITLE
[macOS] Improved exceptions

### LINKED ISSUE #32: [macOS] Catch exceptions that happen in the bluetooth thread, for example when rfcomm channel can't be opened
Currently it fails to catch the error that happen when it connects for example.
This is because the connection happens in a different thread, when the recoverableException is thrown from that thread, it doesn't get catched and thus crashes the client.

This could be solved by passing an error handler to the bluetoothConnector, but I can't get that to work.
My approach was to have a `void` that gets defined in `MacOSBluetoothConnector::MacOSBluetoothConnector`, but that gives an error at compilation: `Reference to non-static member function must be called `.

Used code:
```cpp
// macosbluetoothconnector.mm
MacOSBluetoothConnector::MacOSBluetoothConnector(void (&errorCallback)(RecoverableException))
{
    this->errorHandler = errorCallback;
}
```
```cpp
// macosbluetoothconnector.h
private:
    void *rfcommDevice;
    void *rfcommchannel;
    std::thread* uthread = NULL;
    void errorHandler(RecoverableException);
```

### PR DESCRIPTION
**Pull request by semvis123**
This fixes #32, thanks to @Plutoberth for the suggestion of using a promise.
Now it blocks until the device is fully connected.
Also shows an alert to displays the exception.

[Compiled version](https://github.com/Plutoberth/SonyHeadphonesClient/files/5991141/SonyHeadphonesClient.app.zip)

### CODE REVIEW

File: Client/macos/MacOSBluetoothConnector.mm [hunk 1]
```diff
@@ -63,29 +63,42 @@ -(void)rfcommChannelData:(IOBluetoothRFCOMMChannel *)rfcommChannel data:(void *)
     asyncCommDelegate->delegateCPP = macOSBluetoothConnector;
     // try to open channel
     if ( [device openRFCOMMChannelAsync:&channel withChannelID:rfcommChannelID delegate:asyncCommDelegate] != kIOReturnSuccess ) {
-        throw RecoverableException("Error - could not open the rfcomm.\n", true);
+        RecoverableException exc = RecoverableException("Could not open the rfcomm.", false);
+        std::exception_ptr excPtr = std::make_exception_ptr(exc);
```
Comment (Plutoberth) [inline Client/macos/MacOSBluetoothConnector.mm:67]: when reading the std::make_exception_ptr docs I was kinda terrified for a minute, because I thought that it slices everything to an std::exception 😅

File: Client/macos/MacOSBluetoothConnector.mm [hunk 2]
```diff
@@ -63,29 +63,42 @@ -(void)rfcommChannelData:(IOBluetoothRFCOMMChannel *)rfcommChannel data:(void *)
...
         [device openConnection];
     }
-    // store the device in an variable
+    std::promise<void> connectPromise;
+    std::future<void> connectFuture = connectPromise.get_future();
+
+    // store the device in a variable
     rfcommDevice = (__bridge void*) device;
-    uthread = new std::thread(MacOSBluetoothConnector::connectToMac, this);
+    uthread = new std::thread(MacOSBluetoothConnector::connectToMac, this, std::move(connectPromise));
```
Comment (Plutoberth) [inline Client/macos/MacOSBluetoothConnector.mm:98]: tiny memory leak here. no need to do `new std::thread`, just uthread = std::thread (and make it a value, not a pointer).

**Review by Plutoberth — APPROVED** [review]
cool stuff, just send over the new compiled binary after you do the pointer thing please

File: Client/macos/MacOSBluetoothConnector.mm (hunk 2 above)
Comment (semvis123) [reply Client/macos/MacOSBluetoothConnector.mm]: This should be fixed right now: )

**Comment by Plutoberth** [comment]
Thanks!

**Comment by semvis123** [comment]
No problem, here's a [new compiled version](https://github.com/Plutoberth/SonyHeadphonesClient/files/5991364/SonyHeadphonesClient.app.zip)

**Comment by Plutoberth** [comment]
@semvis123 A [new release](https://github.com/Plutoberth/SonyHeadphonesClient/releases/tag/v1.1.1) was created with the bugfix

**Comment by semvis123** [comment]
Whoops just noticed that you can distribute an app (yes, this is my first time distributing apps lol)
This compiled version is only ~310kb instead of ~650 kb, probably because it removed the debug stuff.
[SonyHeadphonesClient.app.zip](https://github.com/Plutoberth/SonyHeadphonesClient/files/6005527/SonyHeadphonesClient.app.zip)

**Comment by Plutoberth** [comment]
> 
> 
> Whoops just noticed that you can distribute an app (yes, this is my first time distributing apps lol)
> This compiled version is only ~310kb instead of ~650 kb, probably because it removed the debug stuff.
> [SonyHeadphonesClient.app.zip](https://github.com/Plutoberth/SonyHeadphonesClient/files/6005527/SonyHeadphonesClient.app.zip)

OK. I replaced the binary.

**Comment by kieuson93** [comment]
image
I got this issue. Could you guys help check ? Im using WF-SP800N :(

**Comment by Plutoberth** [comment]
@kieuson93 Hi, do you have access to a Windows / Linux PC for testing? I can just make it log all messages from both sides so you could send me a transcript.
